module:
  _target_: emg2qwerty.lightning.GRUCTCModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [264]         # MLP hidden dimensions (can be tuned)
  gru_hidden_size: 512        # GRU hidden size (example value)
  gru_num_layers: 2           # Number of GRU layers (example value)

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context